import { useState } from "react";
import { addRisk } from "../api/endpoints";

const empty = { description: "", probability: 1, impact: 1, mitigation: "", owner: "" };
export default function RiskMatrix({ pilotId, risks = [], onRiskAdded }) {
  const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const tone = (score) => score >= 15 ? "high" : score >= 8 ? "medium" : "low";
  async function submit(event) { event.preventDefault(); setSaving(true); setError(""); try { const risk = await addRisk(pilotId, { ...form, probability: Number(form.probability), impact: Number(form.impact) }); onRiskAdded(risk); setForm(empty); } catch (err) { setError(err.detail || err.message || "Risk could not be added"); } finally { setSaving(false); } }
  return <section className="panel risk-panel"><div className="section-heading"><div><p className="eyebrow">Risk register</p><h2>Operational risks</h2></div></div>{risks.length ? <div className="risk-table-wrap"><table className="review-table risk-table"><thead><tr><th>Description</th><th>Probability</th><th>Impact</th><th>Score</th><th>Mitigation</th><th>Owner</th></tr></thead><tbody>{risks.map((risk) => <tr key={risk.id}><td>{risk.description}</td><td>{risk.probability}</td><td>{risk.impact}</td><td><strong className={`risk-score risk-${tone(risk.score)}`}>{risk.score}</strong></td><td>{risk.mitigation}</td><td>{risk.owner}</td></tr>)}</tbody></table></div> : <div className="state-message">No risks recorded yet.</div>}<form className="risk-form" onSubmit={submit}><input required placeholder="Risk description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><select aria-label="Probability" value={form.probability} onChange={(event) => setForm({ ...form, probability: event.target.value })}>{[1,2,3,4,5].map((value) => <option value={value} key={value}>Probability {value}</option>)}</select><select aria-label="Impact" value={form.impact} onChange={(event) => setForm({ ...form, impact: event.target.value })}>{[1,2,3,4,5].map((value) => <option value={value} key={value}>Impact {value}</option>)}</select><input required placeholder="Mitigation" value={form.mitigation} onChange={(event) => setForm({ ...form, mitigation: event.target.value })} /><input required placeholder="Owner" value={form.owner} onChange={(event) => setForm({ ...form, owner: event.target.value })} /><button className="btn btn-soft" disabled={saving}>{saving ? "Adding…" : "Add risk"}</button></form>{error && <div className="state-message state-error">{error}</div>}</section>;
}
