import { useEffect, useMemo, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { getApplication, getChallenge, getRubric, submitEvaluation } from "../api/endpoints";

export default function EvaluationForm() {
  const { applicationId } = useParams(); const [searchParams] = useSearchParams();
  const [application, setApplication] = useState(null); const [challenge, setChallenge] = useState(null); const [rubric, setRubric] = useState(null);
  const [scores, setScores] = useState({}); const [comments, setComments] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState(null);
  useEffect(() => { let active = true; (async () => { try { const app = await getApplication(applicationId); const challengeId = searchParams.get("challenge_id") || app.challenge_id; if (!challengeId) throw new Error("Challenge context is required to load the evaluation rubric"); const challengeData = await getChallenge(challengeId); const rubricData = await getRubric(challengeData.evaluation_rubric_id); if (!active) return; setApplication(app); setChallenge(challengeData); setRubric(rubricData); setScores(Object.fromEntries((rubricData.criteria || []).map((criterion) => [criterion.key, 50]))); } catch (err) { if (active) setError(err.detail || err.message || "Unable to load evaluation"); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [applicationId, searchParams]);
  const weightedPreview = useMemo(() => rubric?.criteria?.reduce((total, criterion) => total + (scores[criterion.key] ?? 50) * criterion.weight / 100, 0) || 0, [rubric, scores]);
  async function submit(event) { event.preventDefault(); setSubmitting(true); setError(""); try { const response = await submitEvaluation({ application_id: Number(applicationId), scores: Object.fromEntries(rubric.criteria.map((criterion) => [criterion.key, Number(scores[criterion.key] ?? 50)])), comments }); setResult(response); } catch (err) { setError(err.detail || err.message || "Evaluation could not be submitted"); } finally { setSubmitting(false); } }
  return <DashboardLayout role="evaluator" title="Expert Evaluation" subtitle="Score every criterion from the challenge's selected rubric.">{loading ? <div className="state-message">Loading rubric and application…</div> : error && !rubric ? <div className="state-message state-error">{error}</div> : result ? <section className="panel evaluation-confirmation"><p className="eyebrow">Evaluation submitted</p><h2>Score recorded successfully</h2><p>Your weighted score is <strong>{Number(result.weighted_total).toFixed(1)} / 100</strong>. Other experts may independently evaluate this same application.</p><Link className="btn btn-primary" to="/evaluator">Return to reviews</Link></section> : <form className="panel evaluation-form" onSubmit={submit}><div className="evaluation-context"><div><span>Startup</span><strong>{application?.startup_name}</strong></div><div><span>Challenge</span><strong>{challenge?.title}</strong></div><div><span>Rubric</span><strong>{rubric?.name}</strong></div></div>{rubric.criteria.map((criterion) => <label className="evaluation-criterion" key={criterion.key} title={criterion.help || ""}><div><strong>{criterion.label}</strong><span>{criterion.weight}% weight · {scores[criterion.key] ?? 50}/100</span></div><p>{criterion.help}</p><input type="range" min="0" max="100" value={scores[criterion.key] ?? 50} onChange={(event) => setScores((current) => ({ ...current, [criterion.key]: Number(event.target.value) }))} /></label>)}<label className="evaluation-comments">Comments<textarea rows="5" value={comments} onChange={(event) => setComments(event.target.value)} placeholder="Record strengths, risks, and evidence supporting your scores." /></label><div className="total-score"><span>Weighted preview</span><strong>{weightedPreview.toFixed(1)} / 100</strong></div>{error && <div className="state-message state-error">{error}</div>}<button className="btn btn-primary" type="submit" disabled={submitting}>{submitting ? "Submitting evaluation…" : "Submit evaluation"}</button></form>}</DashboardLayout>;
}
