import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { getPilot, submitMilestone } from "../api/endpoints";

export default function MilestoneSubmit() {
  const { pilotId, milestoneId } = useParams(); const navigate = useNavigate();
  const [pilot, setPilot] = useState(null); const [milestone, setMilestone] = useState(null); const [form, setForm] = useState({ evidence_text: "", evidence_url: "", claimed_value: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; getPilot(pilotId).then((data) => { if (!active) return; setPilot(data); setMilestone(data.milestones.find((item) => item.id === Number(milestoneId)) || null); }).catch((err) => active && setError(err.detail || err.message || "Unable to load milestone")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [pilotId, milestoneId]);
  async function submit(event) { event.preventDefault(); setSaving(true); setError(""); try { await submitMilestone(milestoneId, { evidence_text: form.evidence_text, evidence_url: form.evidence_url || null, claimed_value: form.claimed_value === "" ? null : Number(form.claimed_value) }); navigate(`/startup/pilots/${pilotId}`, { state: { notice: "Evidence submitted for independent validation." } }); } catch (err) { setError(err.detail || err.message || "Evidence could not be submitted"); } finally { setSaving(false); } }
  return <DashboardLayout role="startup" title="Submit Milestone Evidence" subtitle="Record delivery evidence and your claimed outcome for independent validation.">{loading ? <div className="state-message">Loading milestone…</div> : error && !pilot ? <div className="state-message state-error">{error}</div> : !milestone ? <div className="state-message">Milestone not found.</div> : <form className="panel milestone-submit-form" onSubmit={submit}><div className="submission-context"><span>Milestone {milestone.seq}</span><h2>{milestone.title}</h2><p>{milestone.deliverable}</p></div><label>Evidence summary<textarea required rows="6" value={form.evidence_text} onChange={(event) => setForm({ ...form, evidence_text: event.target.value })} placeholder="Describe what was delivered and how it can be independently verified." /></label><label>Evidence URL (optional)<input type="url" value={form.evidence_url} onChange={(event) => setForm({ ...form, evidence_url: event.target.value })} placeholder="https://example.com/evidence" /></label><label>Claimed value<input type="number" step="any" value={form.claimed_value} onChange={(event) => setForm({ ...form, claimed_value: event.target.value })} placeholder="Startup's claimed result" /><small>This is your startup's claim. It is not verified until an independent validator reviews it.</small></label>{error && <div className="state-message state-error">{error}</div>}<button className="btn btn-primary" disabled={saving}>{saving ? "Submitting evidence…" : "Submit for validation"}</button></form>}</DashboardLayout>;
}
