import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import Badge from "../components/Badge";
import { getPilot, getProcurement, replicatePilot } from "../api/endpoints";

const tone = (status) => status === "completed" ? "green" : status === "in_progress" ? "amber" : "blue";
export default function Replication() {
  const { id } = useParams(); const [pilot, setPilot] = useState(null); const [rows, setRows] = useState([]); const [districts, setDistricts] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; Promise.all([getPilot(id), getProcurement(id)]).then(([pilotData, procurement]) => { if (!active) return; setPilot(pilotData); setRows(procurement.replication || []); }).catch((err) => active && setError(err.detail || err.message || "Unable to load replication plan")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id]);
  async function submit(event) { event.preventDefault(); const requested = districts.split(",").map((item) => item.trim()).filter(Boolean); if (!requested.length) return; setSaving(true); setError(""); try { const response = await replicatePilot(id, requested); setRows(response.replication); setDistricts(""); } catch (err) { setError(err.detail || err.message || "Districts could not be added"); } finally { setSaving(false); } }
  return <DashboardLayout role="government" title="District Replication" subtitle="Track where a validated solution has completed, started, or is planned.">{loading ? <div className="state-message">Loading replication plan…</div> : error && !pilot ? <div className="state-message state-error">{error}</div> : <><section className="panel"><p className="eyebrow">Source pilot</p><h2>{pilot?.challenge_title}</h2><p>{pilot?.startup_name} · {pilot?.location}</p></section><section className="panel replication-panel"><div className="section-heading"><div><p className="eyebrow">Rollout</p><h2>District status</h2></div><span>{rows.length} districts</span></div>{rows.length ? <table className="review-table"><thead><tr><th>District</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.district}><td><strong>{row.district}</strong></td><td><Badge tone={tone(row.status)}>{row.status}</Badge></td></tr>)}</tbody></table> : <div className="state-message">No replication districts have been added.</div>}<form className="replication-form" onSubmit={submit}><label>Add districts<input value={districts} onChange={(event) => setDistricts(event.target.value)} placeholder="District B, District C" /><small>Separate multiple districts with commas. New rows begin as planned.</small></label><button className="btn btn-primary" disabled={saving}>{saving ? "Adding districts…" : "Add to plan"}</button></form>{error && <div className="state-message state-error">{error}</div>}</section></>}</DashboardLayout>;
}
