import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { finalizePilot, getPilot, getProcurement } from "../api/endpoints";

const decisionCopy = { scale: "Scale", scale_with_modifications: "Scale with modifications", extend_pilot: "Extend pilot", reject: "Reject" };
export default function ScaleUpDecision() {
  const { id } = useParams(); const [pilot, setPilot] = useState(null); const [result, setResult] = useState(null); const [procurement, setProcurement] = useState(null); const [loading, setLoading] = useState(true); const [finalizing, setFinalizing] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; Promise.all([getPilot(id), getProcurement(id)]).then(([pilotData, procurementData]) => { if (!active) return; setPilot(pilotData); setProcurement(procurementData); if (procurementData.decision) setResult({ pilot_id: Number(id), category_scores: {}, weights: {}, final_score: procurementData.final_score, decision: procurementData.decision, justification: procurementData.justification }); }).catch((err) => active && setError(err.detail || err.message || "Unable to load decision data")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id]);
  async function finalize() { setFinalizing(true); setError(""); try { const data = await finalizePilot(id); setResult(data); setProcurement(await getProcurement(id)); } catch (err) { setError(err.detail || err.message || "Pilot could not be finalized"); } finally { setFinalizing(false); } }
  return <DashboardLayout role="government" title="Scale-up Decision" subtitle="Convert verified pilot evidence into an explainable procurement outcome.">{loading ? <div className="state-message">Loading decision evidence…</div> : error && !pilot ? <div className="state-message state-error">{error}</div> : <>{result?.decision ? <section className={`decision-hero decision-${result.decision}`}><p>Final procurement decision</p><h2>{decisionCopy[result.decision] || result.decision}</h2><strong>{Number(result.final_score).toFixed(1)} / 100</strong><span>{result.justification}</span></section> : <section className="panel decision-ready"><h2>{pilot?.challenge_title}</h2><p>Finalize this pilot once KPI measurements, security clearance, and milestone validation are complete.</p><button className="btn btn-primary" disabled={finalizing} onClick={finalize}>{finalizing ? "Computing final decision…" : "Finalize pilot"}</button></section>}{error && <div className="state-message state-error">{error}</div>}{result && Object.keys(result.category_scores || {}).length > 0 && <section className="panel category-score-panel"><div className="section-heading"><div><p className="eyebrow">Explainability</p><h2>Category score breakdown</h2></div></div><div className="category-score-grid">{Object.entries(result.category_scores).map(([key, score]) => <div key={key}><span>{key.replaceAll("_", " ")}</span><strong>{Number(score).toFixed(1)}</strong><small>{result.weights[key]}% weight</small></div>)}</div></section>}{procurement && <section className="panel procurement-checks"><h2>Procurement readiness</h2><div>{Object.entries(procurement.checks || {}).map(([key, passed]) => <span className={passed ? "check-pass" : "check-fail"} key={key}>{passed ? "✓" : "×"} {key.replaceAll("_", " ")}</span>)}</div><p><strong>Recommended pathway:</strong> {procurement.recommended_pathway}</p><Link className="btn btn-soft" to={`/government/pilots/${id}/replication`}>Manage replication</Link></section>}</>}</DashboardLayout>;
}
