import { useEffect, useState } from "react";
import DashboardLayout from "../components/DashboardLayout";
import Badge from "../components/Badge";
import { getPilot, getPilots, validateMilestone } from "../api/endpoints";

export default function ValidatorDashboard() {
  const [reviews, setReviews] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [workingId, setWorkingId] = useState(null);
  async function load() { setLoading(true); setError(""); try { const summaries = await getPilots(); const details = await Promise.all((Array.isArray(summaries) ? summaries : []).map((item) => getPilot(item.id))); setReviews(details.flatMap((pilot) => pilot.milestones.filter((milestone) => ["submitted", "rejected"].includes(milestone.status)).map((milestone) => ({ ...milestone, pilot_id: pilot.id, challenge_title: pilot.challenge_title, startup_name: pilot.startup_name, verified_value_input: milestone.validation?.verified_value ?? "", notes_input: milestone.validation?.notes ?? "" })))); } catch (err) { setError(err.detail || err.message || "Unable to load submitted milestones"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const update = (id, key, value) => setReviews((items) => items.map((item) => item.id === id ? { ...item, [key]: value } : item));
  async function decide(item, verdict) { setWorkingId(item.id); setError(""); try { const response = await validateMilestone(item.id, { verdict, verified_value: item.verified_value_input === "" ? null : Number(item.verified_value_input), notes: item.notes_input }); setReviews((items) => items.map((current) => current.id === item.id ? { ...current, status: response.status, validation: response.validation } : current)); } catch (err) { setError(err.detail || err.message || "Validation could not be submitted"); } finally { setWorkingId(null); } }
  return <DashboardLayout role="validator" title="Independent Validation" subtitle="Compare startup claims with independently verified field evidence.">{loading ? <div className="state-message">Loading submitted milestones…</div> : error && !reviews.length ? <div className="state-message state-error">{error}</div> : !reviews.length ? <div className="state-message">No submitted milestones are awaiting review.</div> : <div className="validation-list">{error && <div className="state-message state-error">{error}</div>}{reviews.map((item) => <article className={`panel validation-card validation-${item.status}`} key={`${item.pilot_id}-${item.id}`}><div className="validation-heading"><div><p className="eyebrow">{item.challenge_title}</p><h2>{item.title}</h2><p>{item.startup_name}</p></div><Badge tone={item.status === "rejected" ? "amber" : "blue"}>{item.status}</Badge></div><p className="validation-evidence">{item.evidence_text}</p><div className="comparison-grid"><div className="claim-box"><span>Startup claimed value</span><strong>{item.claimed_value ?? item.validation?.claimed_value ?? "Not supplied"}</strong><small>Unverified startup submission</small></div><label>Independently verified value<input type="number" step="any" value={item.verified_value_input} onChange={(event) => update(item.id, "verified_value_input", event.target.value)} /><small>Enter the result confirmed by field review.</small></label></div><label>Validation notes<textarea rows="3" value={item.notes_input} onChange={(event) => update(item.id, "notes_input", event.target.value)} /></label>{item.validation && <div className="validation-result"><strong>Verdict: {item.validation.verdict}</strong><span>Claimed {item.validation.claimed_value} · Verified {item.validation.verified_value}</span></div>}<div className="validation-actions"><button className="btn btn-soft" disabled={workingId === item.id} onClick={() => decide(item, "rejected")}>Reject</button><button className="btn btn-primary" disabled={workingId === item.id} onClick={() => decide(item, "approved")}>Approve</button></div></article>)}</div>}</DashboardLayout>;
}
